### ISSUE TITLE
Using with Html2Pdf (TCPDF) 

### ISSUE THREAD

**Issue by ajtsch** [sprain/php-swiss-qr-bill#104]
Hello,

I get the error "must be an instance of TCPDF" when I try using Html2Pdf instead of TCPDF. But as far as I know it is supposed to behave similarly (according to Html2Pdf doc). Is that a bug or am I doing something wrong?

Thanks a lot!

Code:

```
$html2pdf = new Html2Pdf('P', 'A4', 'fr', true, 'UTF-8', array(20, 15, 20, 15));
$html2pdf->writeHTML($content);
	
$output = new QrBill\PaymentPart\Output\TcPdfOutput\TcPdfOutput($qrBill, 'en', $html2pdf);
$output->setPrintable(false)->getPaymentPart();
	
$html2pdf->output($path_bill, 'F');
```

**Comment by sprain** [comment]
When using Html2Pdf you likely want to use `HtmlOutput` instead of `TcPdfOutput`.

**Comment by ajtsch** [comment]
Thanks for the suggestion.

However, I had tried that way but it's not compatible. Html2Pdf can't read the html provided by QrBill (not compliant).

I'll keep searching for other solutions.

**Comment by ajtsch** [comment]
Hello,

Just wondering, will there be someday any fix related to this issue ? 

Thank you

**Comment by sprain** [comment]
If somebody provides a pull request for it, there might.
However, since there has been no other question related to Html2Pdf, interest in it seems to be low.

**Comment by ajtsch** [comment]
I understand. Indeed. May I ask you, would it be possible if I pay you? I don't know if this is something you do or not. My apologies if my request is inappropriate.

At the moment I generate 2 pdfs, one with Html2Pdf and the other with TCPDF for the QR code, then I merge both. It costs in time processing, this is why.

Thank you

**Comment by sprain** [comment]
Thanks for asking. While donations are accepted for this library, I am currently not available for specific individual contract work.

However, since this library is publicly available, others may be able to help you. You might approach a local web development company and ask them to give you support or work on the necessary changes. Or, as a cheaper solution, maybe you can find somebody on Fiverr or similar platforms to do so.

As a basis, it‘s important for you to clearly define in detail what the current issue is that you encounter. This is not yet evident from this task. And maybe – depending on the complexity – that would already be enough for somebody to jump in here and provide an improvement.
