### ISSUE TITLE
Feature Proposal: mPDF Output for creating ZUGFeRD PDF/A-3 Files

### ISSUE THREAD

**Issue by PSchuetz** [sprain/php-swiss-qr-bill#116]
For us, it would be the ultimate solution if we could add an XML attachment for ZUGFeRD to the QR invoices. 
Then all currently existing invoicing needs would be covered. mPDF supports such XML attachments, which means that ZUGFeRD-compatible PDFs could be created directly. 
See https://mpdf.github.io/

In addition, Swiss-QR-Bill would be even more universally usable if we could use a flag to generate the payment section without the QR graphic (for foreign customers). Currently, we have simply created a second TcPdfOutput.php file for this, which removes "$this->addSwissQrCodeImage();".

By the way, it is gratifying that our customers pay QR bills faster! Probably because it's so easy.

**Comment by sprain** [comment]
Thanks for you suggestions!

> In addition, Swiss-QR-Bill would be even more universally usable if we could use a flag to generate the payment section without the QR graphic (for foreign customers).

This is the first time I hear about this approach. Is there some specification which intends a use case like that or is this just how you handle it in order to not confuse foreign customers?

> For us, it would be the ultimate solution if we could add an XML attachment for ZUGFeRD to the QR invoices.
Then all currently existing invoicing needs would be covered. mPDF supports such XML attachments, which means that ZUGFeRD-compatible PDFs could be created directly.

I have no experience with `ZUGFeRD` and cannot estimate how widespread the need for something like this is in combination with qr bills. Maybe others can let us know here whether there is a need?

**Comment by PSchuetz** [comment]
This is probably a concern that does not affect so many users at the moment. We have a wide range of customers from private individuals to international companies (Switzerland and Europe). Large companies (also in Switzerland) increasingly want ZUGFerd compatible documents. Foreign companies can't do anything with the QR graphic. And for us it would be ideal to cover all invoice variants with 1 template.

**Comment by sprain** [comment]
Thanks for the update!

It sounds like a very specific need and not something that should be covered by this library. I suppose that building your own custom `Output` based on this library would be the best solution here.

I leave this issue open so other can tune in if they see a need, too.

**Comment by sprain** [comment]
Closing now due to inactivity.
