### ISSUE TITLE
PNG size is too big, almost 100kb

### ISSUE THREAD

**Issue by ningappa** [sprain/php-swiss-qr-bill#17]
Is there any way to reduce the file size?

**Comment by sprain** [comment]
You are talking about the fully generated qr code png, right?

I don't think there is much to gain. I used Photoshop to re-export some of the reference qr codes as pngs. The file size did become smaller, but the difference was less than 10%.

The main reason for the larger filesize is the following:
The number of blocks within the qr code depends on the saved data. This number often does not match exactly within the size of the qr code. There are two ways to handle this in a png:
* make the qr code smaller than the desired pixel size
* match the qr code with the desired pixel size, but add fuzzy greyscale pixels

Both approaches are unsatisfactory. I decided to use the second approach with fuzzy greyscale pixels for now, because the qr code library in use does not make the actual image smaller along with the qr code, but leaves a white border (but file size goes down to about 10kb).

I see two ways to improve:
* make it configurable, which approach to use, provided a way is found to get rid of the white border
* and even better: add an alternative export way to generate svg images instead

Both are not my main priority for now, but I happily take pull requests for them.

**Comment by sprain** [comment]
Update: I see that the qr code library we use now seems to support logos in svgs. This was not possible when I started making this library. So svg would probably be the best way to go.
https://github.com/endroid/qr-code/pull/173

**Comment by ningappa** [comment]
I have created SVG qr code by changing default writer to svg. the file svg file size is about 200+kb. I converted this svg file to png through some online tool, end up in 20kb of png file.

**Comment by sprain** [comment]
https://github.com/sprain/php-swiss-qr-bill/commit/c2edf1e24bb4553f28b34d1b59f6e4aa694a09e7

Creating qr codes in `SVG` format is now possible.
Run `$qrBill->getQrCode()->writeFile(__DIR__ . '/qr.svg');` to do so.

This does not fix the fact that PNGs have quite large file size. SVG are even bigger, as mentioned above already. Therefore I will leave this issue open.

**Comment by sprain** [comment]
Also see #54

**Comment by sprain** [comment]
I opened a pr in the third-party that we use which would help reducing the file size of png files drastically:
https://github.com/endroid/qr-code/pull/258

**Comment by sdespont** [comment]
@sprain What do you mean by "drastically"?

**Comment by sprain** [comment]
> What do you mean by "drastically"?

90% smaller files.

**Comment by sdespont** [comment]
😮 That's Amazing! In that case, PNG could be used as default QR-Code image format. I hope your PR will be accepted.
