### ISSUE TITLE
 license plate of Liechtenstein as country code...

### ISSUE THREAD

**Issue by auerswald** [sprain/php-swiss-qr-bill#188]
https://github.com/sprain/php-swiss-qr-bill/blob/c59dc1d08e2006c400bf7d0c16bc4e972b643323/src/DataGroup/Element/StructuredAddress.php#L142

`FL` is the license plate of Liechtenstein, but not the country code... :nerd_face:

```php
if (in_array($this->getCountry(), ['CH', 'LI'])) {
    // ...
}
```

**Comment by auerswald** [comment]
same error in:

https://github.com/sprain/php-swiss-qr-bill/blob/c59dc1d08e2006c400bf7d0c16bc4e972b643323/src/DataGroup/Element/StructuredAddress.php#L142

**Comment by auerswald** [comment]
PR https://github.com/sprain/php-swiss-qr-bill/pull/189

**Comment by markus-ksg** [comment]
Please reopen.

The country code of Liechtenstein is indeed 'LI', but the code actually only produced the correct result **before** the fix (by accident, because 'FL' is no valid country).

https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf says: "For invoicing to countries outside Switzerland, including Lichtenstein[sic!], the country code should be printed on the payment section."

I.e. the correct fix would have been to replace the whole
`in_array($this->getCountry(), ['CH', 'FL'])`
with
`$this->getCountry() === 'CH'

The `CombinedAddressTest` and `StructuredAddressTest` should also be fixed to expect `\nLI-9490 Vaduz`.
