### ISSUE TITLE
New QR-IID validation for TYPE_QR

### ISSUE THREAD

**Issue by Franco2911** [sprain/php-swiss-qr-bill#25]
Hello,
It seems that there is an error in the validation of the IBAN QR.
I tested several new IBAN and I get the error: 

> The payment reference type "QRR" does not match with the iban type of "CH6730808000011857077". This is not a valid International Bank Account Number (IBAN).

The Raiffeisen Bank indicate that the only change between IBAN QR and IBAN is the second part with 3000 - 31999.

Please have a look here, Maybe I'm wrong...

[RAIFFEISEN QR](https://www.raiffeisen.ch/neuchatel-et-vallees/de/firmenkunden/liquiditaet-und-zahlungsverkehr/harmonisierung-zahlungsverkehr/qr-rechnung/was-ist-qr-rechnung.html)
You can find this example:

> Beispiel QR-IBAN mit QR-IID:
CH12 3080 8001 2345 6789 0

Beispiel IBAN mit IID:
CH21 8080 8 001 2345 6789 0

Franco

**Comment by sprain** [comment]
Thanks for reporting!

The fact that the IBAN example [on the Raiffeisen website](https://www.raiffeisen.ch/neuchatel-et-vallees/de/firmenkunden/liquiditaet-und-zahlungsverkehr/harmonisierung-zahlungsverkehr/qr-rechnung/was-ist-qr-rechnung.html) all end with `1234567890` make me come to the conclusion that they are, in fact, invalid. Also the normal IBAN with IID fails [IBAN checks](https://bank.codes/iban/validate/).

I suppose, those IBAN examples only serve the purpose to show the difference between QR-IBANs and normal IBAN, but are not supposed to be actually valid.

Since real QR-IBAN codes are hard to find yet, to play around with QR-IBAN examples, try the one that is available on the example qr payment parts: `CH44 3199 9123 0008 8901 2`.

Feel free to re-open this issue if you think I am mistaken with my conclusion.

**Comment by Franco2911** [comment]
Thank for your answere,
I think you're right.
You can test your qrcode on this virtual testing platforme by UBS.
[UBS TEST BANK](https://ubs-paymentstandards.ch/#!QRBillMainView/BILLER)
You can find a lot of example qrid.

Let me know if this is helpful for you

Best regards

**Comment by eschiendorfer** [comment]
@Franco2911 Have you resolved this issue? I want to setup QR-IBAN for Raiffeisen Bank and I tried to use this replacement of 8 with 3, but that doesn't seem to work. 

So what is now the case? Is the QR-IBAN really just wrong?

**Comment by Franco2911** [comment]
Hello,
The fact is that you have to use the QRIban the Raiffeisen send to you, Indeed you can't just change the iban of the account to obtain a QRIban, it is assigned and sent to you by the Raiffeisen bank.

Only for The Raiffeisen : 

1. They changed the IBAN (account number not QRIban)
2. The QrIban is not begening with 81 or 12

Here is one QRIban that works with this library : CH21308080048********

It seems that the new IBAN are not aleready in use, One of my clients had to go back to the old IBAN and then go back to the new one after calling the bank and asked to change it to the new one.
This only concerns the Raiffeisen bank.

I hop, this can help you.

**Comment by eschiendorfer** [comment]
I found the QR-IBAN finally in the Raiffeisen Account. You have to "pretend" that you want to order pre printed QR Invoices. There you will get the QR-IBAN. In my case it was really just CH81 to CH12 and 8080 to 3080.
