### ISSUE TITLE
example_scor.php fires Call to undefined function kmukku\phpIso11649\bcmod()

### ISSUE THREAD

**Issue by dkameleon** [sprain/php-swiss-qr-bill#256]
I tried example_scor.php with output as HTML, but faced an issue:

Uncaught Error: Call to undefined function kmukku\phpIso11649\bcmod() in [__ROOT__]/vendor/kmukku/php-iso11649/src/phpIso11649.php:47
Stack trace:
#0 [__ROOT__]/vendor/kmukku/php-iso11649/src/phpIso11649.php(54): kmukku\phpIso11649\phpIso11649->calculateRfChecksum()
#1 [__ROOT__]/vendor/sprain/swiss-qr-bill/src/Reference/RfCreditorReferenceGenerator.php(41): kmukku\phpIso11649\phpIso11649->generateRfReference()
#2 [__ROOT__]/vendor/sprain/swiss-qr-bill/src/Reference/RfCreditorReferenceGenerator.php(23): Sprain\SwissQrBill\Reference\RfCreditorReferenceGenerator->doGenerate()
#3 [__SITE__]/classes/finances/ClassOwlQrBill.php(59): Sprain\SwissQrBill\Reference\RfCreditorReferenceGenerator::generate()

This is what I have installed recently:

kmukku/php-iso11649              1.6       ISO 11649 creditor reference library for php
sprain/swiss-qr-bill             v4.10     A PHP library to create Swiss QR bills

**Comment by sprain** [comment]
The function `bcmod()` is part of the PHP `bcmath` extension. This extension is likely missing from your PHP installation.

You can check by running `php -m` on your console and see if `bcmath` is listed there.
You can also run `composer check-platform-reqs` to check if your setup matches the requirements defined by the libraries you use.

If not, you either need to recompile PHP with the required extensions or get in touch with your hoster for help. Any support regarding this topic would be beyond of what we can do here.

If you still feel the issue comes from this library, please provide the output from the two commands mentioned above.

**Comment by dkameleon** [comment]
Here is `composer check-platform-reqs` output i got before installing bcmath:
![image](https://github.com/sprain/php-swiss-qr-bill/assets/238825/c97cbb5d-ebc9-4e0d-80eb-dabeae928cb1)

But after installing `bcmath` it started working as it suppose to. 
Thank you!
I was confused with namespaced path to **kmukku\phpIso11649\bcmod()** and thought it is some internal function.

**Comment by gagarine** [comment]
FYI I did a pull request upstream to avoid bcmath dependency https://github.com/kmukku/php-iso11649/pull/10
