### ISSUE TITLE
AdditionalInformation: multiline

### ISSUE THREAD

**Issue by rgendroz** [sprain/php-swiss-qr-bill#82]
First of all, thanks again for this good and useful project .-)

Then, I have a question about multiline on AdditionalInformation field:

On postfinance, seems to be truncate on 35 characters, so if I try with this string (4x35= 140)

```
        $qrBill->setAdditionalInformation(
            QrBill\DataGroup\Element\AdditionalInformation::create(
                'First AdditionalInformation line 01First AdditionalInformation line 02First AdditionalInformation line 03First AdditionalInformation line 04'
            )
        );
```
it looks like this on efinance mobile app:

![image](https://user-images.githubusercontent.com/49240897/91355856-109ac580-e7ef-11ea-8fd1-d6ac10282af0.png)

Would you have an issue to force multiline before 35 caracters?

I think it could like something like this: 

```
        $qrBill->setAdditionalInformation(
            QrBill\DataGroup\Element\AdditionalInformation::create(
                'First AdditionalInformation line 01', 
                'First AdditionalInformation line 02', 
                'First AdditionalInformation line 03', 
                'First AdditionalInformation line 04' 
            )
        );
```
Thanks a lot, with regards.

**Comment by sprain** [comment]
Hi @rgendroz, thanks for this input.

Is the screenshot that you provided the result after scanning a qr bill in PostFinance?
The specifications only define that the `unstructured message` may contain a max of 140 characters ([see page 29 of this document](https://github.com/sprain/php-swiss-qr-bill/blob/master/docs/specs/ig-qr-bill-en-v2.1.pdf)). If PostFinance splits this up into multiple lines, then it might be their own interpretation of how to display that information to the user. But I would like to confirm that this really is what they are doing here.

Then your suggested implementation would be a bc break, because there already is a second parameter to provide the optional `bill information`. So even we did change it to provide multiple lines, I'd prefer to find a different approach.

For now, I'd be happy if you and other people maybe can confirm what PostFinance and other banks do with the `unstructured message` text. 

I personally use UBS, and there it is just one string. Interestingly it is a `message to the receiver`, while I would have expected it to be a message intended for the payer … I have the feeling, there is still a lot of room for interpretation of the specification by the single banks.

![IMG_0939](https://user-images.githubusercontent.com/260361/91421477-44f59c80-e856-11ea-8a3f-74d30b11347e.jpg)

**Comment by sprain** [comment]
Here is a test invoice that could be used to see what single banks do with the additional information:
https://github.com/sprain/php-swiss-qr-bill/blob/master/tests/TestData/FpdfOutput/qr-additional-information.pdf

**Comment by fabian** [comment]
Raiffeisen also uses it as a message for the receiver. Part of the message even gets lost (might be a bug?):

<img width="911" alt="Screenshot 2020-08-27 at 11 27 11" src="https://user-images.githubusercontent.com/13346/91423081-593a9900-e858-11ea-8565-675382dc9bd6.png">

**Comment by sprain** [comment]
> Part of the message even gets lost (might be a bug?):

Thank you @fabian !
It is correct, because "Bill information" is actually something else.

**Comment by rgendroz** [comment]
Thanks for your reply @sprain, and sorry for my late answer...
I have no evidences but I think Postfinance parse the original field in multiple lines for their user's comfort in mobile app .-)

**Comment by sprain** [comment]
Closing this as there seems to be no issue.
